// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChFaqgXmYbhpBUXJwRP8ql0jkPsgMPu2Y',
    appId: '1:779096210262:web:06dda168532856c49434f7',
    messagingSenderId: '779096210262',
    projectId: 'famzytourz-production',
    authDomain: 'famzytourz-production.firebaseapp.com',
    storageBucket: 'famzytourz-production.firebasestorage.app',
    measurementId: 'G-0WN42R0LL2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgHYbx9cme-8nqjD2AZXcU2sEXztQ9CQs',
    appId: '1:779096210262:android:1b6dbf9949dd0e4f9434f7',
    messagingSenderId: '779096210262',
    projectId: 'famzytourz-production',
    storageBucket: 'famzytourz-production.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDqg06dno-vMuUMghGiBupjRIA5ru5PnE',
    appId: '1:779096210262:ios:18a758f14eacbd4e9434f7',
    messagingSenderId: '779096210262',
    projectId: 'famzytourz-production',
    storageBucket: 'famzytourz-production.firebasestorage.app',
    iosBundleId: 'com.example.famzyTourzV2',
  );
}
